### ISSUE TITLE
How do I start a Node from a snapshot

### ISSUE THREAD

**Issue by COLUD4** [telosnetwork/node-template#18]
I can't find the snapshot download link

**Comment by poplexity** [comment]
https://t.me/TelosTestnet is a good place to ask, there's a number of BPs who offer snapshots available for download.  Check the pinned message in that channel.

**Comment by COLUD4** [comment]
I searched and asked in Discord and couldn't find a link to download the snapshot. Can you just send me a download link? Thank you very much!
